Repository nuclear-multimessenger-astronomy/nmma, pull requests merged in 2023-07, with the labels that each got.

#162 consolidate lightcurve generation code
  nmma/em/analysis.py
Labels: enhancement

#163 Update .gitignore
  .gitignore
Labels: repo

#180 Update docs
  .github/workflows/python-package.yml
  doc/installation.md
Labels: documentation
